add_executable(forgeadingdb_core_test core_test.cpp)
target_link_libraries(forgeadingdb_core_test PRIVATE forgeadingdb_core)

add_executable(forgeadingdb_page_test storage/page_test.cpp)
target_link_libraries(forgeadingdb_page_test PRIVATE forgeadingdb_core)

add_executable(forgeadingdb_disk_manager_test storage/disk_manager_test.cpp)
target_link_libraries(forgeadingdb_disk_manager_test PRIVATE forgeadingdb_core)

add_executable(
  forgeadingdb_buffer_pool_manager_test
  storage/buffer_pool_manager_test.cpp
)
target_link_libraries(
  forgeadingdb_buffer_pool_manager_test
  PRIVATE forgeadingdb_core
)

add_executable(forgeadingdb_lru_replacer_test storage/lru_replacer_test.cpp)
target_link_libraries(forgeadingdb_lru_replacer_test PRIVATE forgeadingdb_core)

add_test(NAME forgeadingdb.core COMMAND forgeadingdb_core_test)
add_test(NAME forgeadingdb.page COMMAND forgeadingdb_page_test)
add_test(NAME forgeadingdb.disk_manager COMMAND forgeadingdb_disk_manager_test)
add_test(
  NAME forgeadingdb.buffer_pool_manager
  COMMAND forgeadingdb_buffer_pool_manager_test
)
add_test(NAME forgeadingdb.lru_replacer COMMAND forgeadingdb_lru_replacer_test)
add_test(NAME forgeadingdb.version COMMAND forgeadingdb --version)
